package com.nhatnguyen.pojo;
// Generated Dec 4, 2016 9:17:20 PM by Hibernate Tools 3.6.0.Final

import java.util.Arrays;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MerchantSummaryId generated by hbm2java
 */
@Embeddable
public class MerchantSummaryId implements java.io.Serializable {

	private byte[] merchantNumber;
	private Date reportDate;

	public MerchantSummaryId() {
	}

	public MerchantSummaryId(byte[] merchantNumber, Date reportDate) {
		this.merchantNumber = merchantNumber;
		this.reportDate = reportDate;
	}

	@Column(name = "MERCHANT_NUMBER", nullable = false)
	public byte[] getMerchantNumber() {
		return this.merchantNumber;
	}

	public void setMerchantNumber(byte[] merchantNumber) {
		this.merchantNumber = merchantNumber;
	}

	@Column(name = "REPORT_DATE", nullable = false, length = 10)
	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MerchantSummaryId))
			return false;
		MerchantSummaryId castOther = (MerchantSummaryId) other;

		return ((this.getMerchantNumber() == castOther.getMerchantNumber())
				|| (this.getMerchantNumber() != null && castOther.getMerchantNumber() != null
						&& Arrays.equals(this.getMerchantNumber(), castOther.getMerchantNumber())))
				&& ((this.getReportDate() == castOther.getReportDate())
						|| (this.getReportDate() != null && castOther.getReportDate() != null
								&& this.getReportDate().equals(castOther.getReportDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMerchantNumber() == null ? 0 : Arrays.hashCode(this.getMerchantNumber()));
		result = 37 * result + (getReportDate() == null ? 0 : this.getReportDate().hashCode());
		return result;
	}

}
