package com.nhatnguyen.pojo;
// Generated Dec 4, 2016 9:17:20 PM by Hibernate Tools 3.6.0.Final

import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MerchantSummary generated by hbm2java
 */
@Entity
@Table(name = "MERCHANT_SUMMARY")
public class MerchantSummary implements Serializable {

	private MerchantSummaryId id;
	private Merchant merchant;
	private int transactionCount;
	private int salesCount;
	private long salesAmount;
	private int returnCount;
	private long returnAmount;
	private long netAmount;
	private int keyedCount;
	private long keyAmount;
	private int foreignCardCount;
	private int foreignCardSalesCount;
	private int foreignCardReturnCount;
	private long foreignCardSalesAmount;
	private long foreignCardReturnAmount;
	private long foreignCardNetAmount;
	private int debitCardCount;
	private int debitCardSalesCount;
	private int debitCardReturnCount;
	private long debitCardSalesAmount;
	private long debitCardReturnAmount;
	private long debitCardNetAmount;
	private int visaCardCount;
	private int visaCardSalesCount;
	private int visaCardReturnCount;
	private long visaCardSalesAmount;
	private long visaCardReturnAmount;
	private long visaCardNetAmount;
	private int masterCardCount;
	private int masterCardSalesCount;
	private int masterCardReturnCount;
	private long masterCardSalesAmount;
	private long masterCardReturnAmount;
	private long masterCardNetAmount;
	private int americanexpressCardCount;
	private int americanexpressCardSalesCount;
	private int americanexpressCardReturnCount;
	private long americanexpressCardSalesAmount;
	private long americanexpressCardReturnAmount;
	private long americanexpressCardNetAmount;
	private int discoveryCardCount;
	private int discoveryCardSalesCount;
	private int discoveryCardReturnCount;
	private long discoveryCardSalesAmount;
	private long discoveryCardReturnAmount;
	private long discoveryCardNetAmount;
	private int otherCardCount;
	private int otherCardSalesCount;
	private int otherCardReturnCount;
	private long otherCardSalesAmount;
	private long otherCardReturnAmount;
	private long otherCardNetAmount;

	public MerchantSummary() {
	}

	public MerchantSummary(MerchantSummaryId id, Merchant merchant, int transactionCount, int salesCount,
			long salesAmount, int returnCount, long returnAmount, long netAmount, int keyedCount, long keyAmount,
			int foreignCardCount, int foreignCardSalesCount, int foreignCardReturnCount, long foreignCardSalesAmount,
			long foreignCardReturnAmount, long foreignCardNetAmount, int debitCardCount, int debitCardSalesCount,
			int debitCardReturnCount, long debitCardSalesAmount, long debitCardReturnAmount, long debitCardNetAmount,
			int visaCardCount, int visaCardSalesCount, int visaCardReturnCount, long visaCardSalesAmount,
			long visaCardReturnAmount, long visaCardNetAmount, int masterCardCount, int masterCardSalesCount,
			int masterCardReturnCount, long masterCardSalesAmount, long masterCardReturnAmount,
			long masterCardNetAmount, int americanexpressCardCount, int americanexpressCardSalesCount,
			int americanexpressCardReturnCount, long americanexpressCardSalesAmount,
			long americanexpressCardReturnAmount, long americanexpressCardNetAmount, int discoveryCardCount,
			int discoveryCardSalesCount, int discoveryCardReturnCount, long discoveryCardSalesAmount,
			long discoveryCardReturnAmount, long discoveryCardNetAmount, int otherCardCount, int otherCardSalesCount,
			int otherCardReturnCount, long otherCardSalesAmount, long otherCardReturnAmount, long otherCardNetAmount) {
		this.id = id;
		this.merchant = merchant;
		this.transactionCount = transactionCount;
		this.salesCount = salesCount;
		this.salesAmount = salesAmount;
		this.returnCount = returnCount;
		this.returnAmount = returnAmount;
		this.netAmount = netAmount;
		this.keyedCount = keyedCount;
		this.keyAmount = keyAmount;
		this.foreignCardCount = foreignCardCount;
		this.foreignCardSalesCount = foreignCardSalesCount;
		this.foreignCardReturnCount = foreignCardReturnCount;
		this.foreignCardSalesAmount = foreignCardSalesAmount;
		this.foreignCardReturnAmount = foreignCardReturnAmount;
		this.foreignCardNetAmount = foreignCardNetAmount;
		this.debitCardCount = debitCardCount;
		this.debitCardSalesCount = debitCardSalesCount;
		this.debitCardReturnCount = debitCardReturnCount;
		this.debitCardSalesAmount = debitCardSalesAmount;
		this.debitCardReturnAmount = debitCardReturnAmount;
		this.debitCardNetAmount = debitCardNetAmount;
		this.visaCardCount = visaCardCount;
		this.visaCardSalesCount = visaCardSalesCount;
		this.visaCardReturnCount = visaCardReturnCount;
		this.visaCardSalesAmount = visaCardSalesAmount;
		this.visaCardReturnAmount = visaCardReturnAmount;
		this.visaCardNetAmount = visaCardNetAmount;
		this.masterCardCount = masterCardCount;
		this.masterCardSalesCount = masterCardSalesCount;
		this.masterCardReturnCount = masterCardReturnCount;
		this.masterCardSalesAmount = masterCardSalesAmount;
		this.masterCardReturnAmount = masterCardReturnAmount;
		this.masterCardNetAmount = masterCardNetAmount;
		this.americanexpressCardCount = americanexpressCardCount;
		this.americanexpressCardSalesCount = americanexpressCardSalesCount;
		this.americanexpressCardReturnCount = americanexpressCardReturnCount;
		this.americanexpressCardSalesAmount = americanexpressCardSalesAmount;
		this.americanexpressCardReturnAmount = americanexpressCardReturnAmount;
		this.americanexpressCardNetAmount = americanexpressCardNetAmount;
		this.discoveryCardCount = discoveryCardCount;
		this.discoveryCardSalesCount = discoveryCardSalesCount;
		this.discoveryCardReturnCount = discoveryCardReturnCount;
		this.discoveryCardSalesAmount = discoveryCardSalesAmount;
		this.discoveryCardReturnAmount = discoveryCardReturnAmount;
		this.discoveryCardNetAmount = discoveryCardNetAmount;
		this.otherCardCount = otherCardCount;
		this.otherCardSalesCount = otherCardSalesCount;
		this.otherCardReturnCount = otherCardReturnCount;
		this.otherCardSalesAmount = otherCardSalesAmount;
		this.otherCardReturnAmount = otherCardReturnAmount;
		this.otherCardNetAmount = otherCardNetAmount;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "merchantNumber", column = @Column(name = "MERCHANT_NUMBER", nullable = false)),
			@AttributeOverride(name = "reportDate", column = @Column(name = "REPORT_DATE", nullable = false, length = 10)) })
	public MerchantSummaryId getId() {
		return this.id;
	}

	public void setId(MerchantSummaryId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MERCHANT_NUMBER", nullable = false, insertable = false, updatable = false)
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@Column(name = "TRANSACTION_COUNT", nullable = false)
	public int getTransactionCount() {
		return this.transactionCount;
	}

	public void setTransactionCount(int transactionCount) {
		this.transactionCount = transactionCount;
	}

	@Column(name = "SALES_COUNT", nullable = false)
	public int getSalesCount() {
		return this.salesCount;
	}

	public void setSalesCount(int salesCount) {
		this.salesCount = salesCount;
	}

	@Column(name = "SALES_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getSalesAmount() {
		return this.salesAmount;
	}

	public void setSalesAmount(long salesAmount) {
		this.salesAmount = salesAmount;
	}

	@Column(name = "RETURN_COUNT", nullable = false)
	public int getReturnCount() {
		return this.returnCount;
	}

	public void setReturnCount(int returnCount) {
		this.returnCount = returnCount;
	}

	@Column(name = "RETURN_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getReturnAmount() {
		return this.returnAmount;
	}

	public void setReturnAmount(long returnAmount) {
		this.returnAmount = returnAmount;
	}

	@Column(name = "NET_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getNetAmount() {
		return this.netAmount;
	}

	public void setNetAmount(long netAmount) {
		this.netAmount = netAmount;
	}

	@Column(name = "KEYED_COUNT", nullable = false)
	public int getKeyedCount() {
		return this.keyedCount;
	}

	public void setKeyedCount(int keyedCount) {
		this.keyedCount = keyedCount;
	}

	@Column(name = "KEY_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getKeyAmount() {
		return this.keyAmount;
	}

	public void setKeyAmount(long keyAmount) {
		this.keyAmount = keyAmount;
	}

	@Column(name = "FOREIGN_CARD_COUNT", nullable = false)
	public int getForeignCardCount() {
		return this.foreignCardCount;
	}

	public void setForeignCardCount(int foreignCardCount) {
		this.foreignCardCount = foreignCardCount;
	}

	@Column(name = "FOREIGN_CARD_SALES_COUNT", nullable = false)
	public int getForeignCardSalesCount() {
		return this.foreignCardSalesCount;
	}

	public void setForeignCardSalesCount(int foreignCardSalesCount) {
		this.foreignCardSalesCount = foreignCardSalesCount;
	}

	@Column(name = "FOREIGN_CARD_RETURN_COUNT", nullable = false)
	public int getForeignCardReturnCount() {
		return this.foreignCardReturnCount;
	}

	public void setForeignCardReturnCount(int foreignCardReturnCount) {
		this.foreignCardReturnCount = foreignCardReturnCount;
	}

	@Column(name = "FOREIGN_CARD_SALES_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getForeignCardSalesAmount() {
		return this.foreignCardSalesAmount;
	}

	public void setForeignCardSalesAmount(long foreignCardSalesAmount) {
		this.foreignCardSalesAmount = foreignCardSalesAmount;
	}

	@Column(name = "FOREIGN_CARD_RETURN_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getForeignCardReturnAmount() {
		return this.foreignCardReturnAmount;
	}

	public void setForeignCardReturnAmount(long foreignCardReturnAmount) {
		this.foreignCardReturnAmount = foreignCardReturnAmount;
	}

	@Column(name = "FOREIGN_CARD_NET_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getForeignCardNetAmount() {
		return this.foreignCardNetAmount;
	}

	public void setForeignCardNetAmount(long foreignCardNetAmount) {
		this.foreignCardNetAmount = foreignCardNetAmount;
	}

	@Column(name = "DEBIT_CARD_COUNT", nullable = false)
	public int getDebitCardCount() {
		return this.debitCardCount;
	}

	public void setDebitCardCount(int debitCardCount) {
		this.debitCardCount = debitCardCount;
	}

	@Column(name = "DEBIT_CARD_SALES_COUNT", nullable = false)
	public int getDebitCardSalesCount() {
		return this.debitCardSalesCount;
	}

	public void setDebitCardSalesCount(int debitCardSalesCount) {
		this.debitCardSalesCount = debitCardSalesCount;
	}

	@Column(name = "DEBIT_CARD_RETURN_COUNT", nullable = false)
	public int getDebitCardReturnCount() {
		return this.debitCardReturnCount;
	}

	public void setDebitCardReturnCount(int debitCardReturnCount) {
		this.debitCardReturnCount = debitCardReturnCount;
	}

	@Column(name = "DEBIT_CARD_SALES_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getDebitCardSalesAmount() {
		return this.debitCardSalesAmount;
	}

	public void setDebitCardSalesAmount(long debitCardSalesAmount) {
		this.debitCardSalesAmount = debitCardSalesAmount;
	}

	@Column(name = "DEBIT_CARD_RETURN_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getDebitCardReturnAmount() {
		return this.debitCardReturnAmount;
	}

	public void setDebitCardReturnAmount(long debitCardReturnAmount) {
		this.debitCardReturnAmount = debitCardReturnAmount;
	}

	@Column(name = "DEBIT_CARD_NET_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getDebitCardNetAmount() {
		return this.debitCardNetAmount;
	}

	public void setDebitCardNetAmount(long debitCardNetAmount) {
		this.debitCardNetAmount = debitCardNetAmount;
	}

	@Column(name = "VISA_CARD_COUNT", nullable = false)
	public int getVisaCardCount() {
		return this.visaCardCount;
	}

	public void setVisaCardCount(int visaCardCount) {
		this.visaCardCount = visaCardCount;
	}

	@Column(name = "VISA_CARD_SALES_COUNT", nullable = false)
	public int getVisaCardSalesCount() {
		return this.visaCardSalesCount;
	}

	public void setVisaCardSalesCount(int visaCardSalesCount) {
		this.visaCardSalesCount = visaCardSalesCount;
	}

	@Column(name = "VISA_CARD_RETURN_COUNT", nullable = false)
	public int getVisaCardReturnCount() {
		return this.visaCardReturnCount;
	}

	public void setVisaCardReturnCount(int visaCardReturnCount) {
		this.visaCardReturnCount = visaCardReturnCount;
	}

	@Column(name = "VISA_CARD_SALES_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getVisaCardSalesAmount() {
		return this.visaCardSalesAmount;
	}

	public void setVisaCardSalesAmount(long visaCardSalesAmount) {
		this.visaCardSalesAmount = visaCardSalesAmount;
	}

	@Column(name = "VISA_CARD_RETURN_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getVisaCardReturnAmount() {
		return this.visaCardReturnAmount;
	}

	public void setVisaCardReturnAmount(long visaCardReturnAmount) {
		this.visaCardReturnAmount = visaCardReturnAmount;
	}

	@Column(name = "VISA_CARD_NET_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getVisaCardNetAmount() {
		return this.visaCardNetAmount;
	}

	public void setVisaCardNetAmount(long visaCardNetAmount) {
		this.visaCardNetAmount = visaCardNetAmount;
	}

	@Column(name = "MASTER_CARD_COUNT", nullable = false)
	public int getMasterCardCount() {
		return this.masterCardCount;
	}

	public void setMasterCardCount(int masterCardCount) {
		this.masterCardCount = masterCardCount;
	}

	@Column(name = "MASTER_CARD_SALES_COUNT", nullable = false)
	public int getMasterCardSalesCount() {
		return this.masterCardSalesCount;
	}

	public void setMasterCardSalesCount(int masterCardSalesCount) {
		this.masterCardSalesCount = masterCardSalesCount;
	}

	@Column(name = "MASTER_CARD_RETURN_COUNT", nullable = false)
	public int getMasterCardReturnCount() {
		return this.masterCardReturnCount;
	}

	public void setMasterCardReturnCount(int masterCardReturnCount) {
		this.masterCardReturnCount = masterCardReturnCount;
	}

	@Column(name = "MASTER_CARD_SALES_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getMasterCardSalesAmount() {
		return this.masterCardSalesAmount;
	}

	public void setMasterCardSalesAmount(long masterCardSalesAmount) {
		this.masterCardSalesAmount = masterCardSalesAmount;
	}

	@Column(name = "MASTER_CARD_RETURN_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getMasterCardReturnAmount() {
		return this.masterCardReturnAmount;
	}

	public void setMasterCardReturnAmount(long masterCardReturnAmount) {
		this.masterCardReturnAmount = masterCardReturnAmount;
	}

	@Column(name = "MASTER_CARD_NET_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getMasterCardNetAmount() {
		return this.masterCardNetAmount;
	}

	public void setMasterCardNetAmount(long masterCardNetAmount) {
		this.masterCardNetAmount = masterCardNetAmount;
	}

	@Column(name = "AMERICANEXPRESS_CARD_COUNT", nullable = false)
	public int getAmericanexpressCardCount() {
		return this.americanexpressCardCount;
	}

	public void setAmericanexpressCardCount(int americanexpressCardCount) {
		this.americanexpressCardCount = americanexpressCardCount;
	}

	@Column(name = "AMERICANEXPRESS_CARD_SALES_COUNT", nullable = false)
	public int getAmericanexpressCardSalesCount() {
		return this.americanexpressCardSalesCount;
	}

	public void setAmericanexpressCardSalesCount(int americanexpressCardSalesCount) {
		this.americanexpressCardSalesCount = americanexpressCardSalesCount;
	}

	@Column(name = "AMERICANEXPRESS_CARD_RETURN_COUNT", nullable = false)
	public int getAmericanexpressCardReturnCount() {
		return this.americanexpressCardReturnCount;
	}

	public void setAmericanexpressCardReturnCount(int americanexpressCardReturnCount) {
		this.americanexpressCardReturnCount = americanexpressCardReturnCount;
	}

	@Column(name = "AMERICANEXPRESS_CARD_SALES_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getAmericanexpressCardSalesAmount() {
		return this.americanexpressCardSalesAmount;
	}

	public void setAmericanexpressCardSalesAmount(long americanexpressCardSalesAmount) {
		this.americanexpressCardSalesAmount = americanexpressCardSalesAmount;
	}

	@Column(name = "AMERICANEXPRESS_CARD_RETURN_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getAmericanexpressCardReturnAmount() {
		return this.americanexpressCardReturnAmount;
	}

	public void setAmericanexpressCardReturnAmount(long americanexpressCardReturnAmount) {
		this.americanexpressCardReturnAmount = americanexpressCardReturnAmount;
	}

	@Column(name = "AMERICANEXPRESS_CARD_NET_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getAmericanexpressCardNetAmount() {
		return this.americanexpressCardNetAmount;
	}

	public void setAmericanexpressCardNetAmount(long americanexpressCardNetAmount) {
		this.americanexpressCardNetAmount = americanexpressCardNetAmount;
	}

	@Column(name = "DISCOVERY_CARD_COUNT", nullable = false)
	public int getDiscoveryCardCount() {
		return this.discoveryCardCount;
	}

	public void setDiscoveryCardCount(int discoveryCardCount) {
		this.discoveryCardCount = discoveryCardCount;
	}

	@Column(name = "DISCOVERY_CARD_SALES_COUNT", nullable = false)
	public int getDiscoveryCardSalesCount() {
		return this.discoveryCardSalesCount;
	}

	public void setDiscoveryCardSalesCount(int discoveryCardSalesCount) {
		this.discoveryCardSalesCount = discoveryCardSalesCount;
	}

	@Column(name = "DISCOVERY_CARD_RETURN_COUNT", nullable = false)
	public int getDiscoveryCardReturnCount() {
		return this.discoveryCardReturnCount;
	}

	public void setDiscoveryCardReturnCount(int discoveryCardReturnCount) {
		this.discoveryCardReturnCount = discoveryCardReturnCount;
	}

	@Column(name = "DISCOVERY_CARD_SALES_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getDiscoveryCardSalesAmount() {
		return this.discoveryCardSalesAmount;
	}

	public void setDiscoveryCardSalesAmount(long discoveryCardSalesAmount) {
		this.discoveryCardSalesAmount = discoveryCardSalesAmount;
	}

	@Column(name = "DISCOVERY_CARD_RETURN_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getDiscoveryCardReturnAmount() {
		return this.discoveryCardReturnAmount;
	}

	public void setDiscoveryCardReturnAmount(long discoveryCardReturnAmount) {
		this.discoveryCardReturnAmount = discoveryCardReturnAmount;
	}

	@Column(name = "DISCOVERY_CARD_NET_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getDiscoveryCardNetAmount() {
		return this.discoveryCardNetAmount;
	}

	public void setDiscoveryCardNetAmount(long discoveryCardNetAmount) {
		this.discoveryCardNetAmount = discoveryCardNetAmount;
	}

	@Column(name = "OTHER_CARD_COUNT", nullable = false)
	public int getOtherCardCount() {
		return this.otherCardCount;
	}

	public void setOtherCardCount(int otherCardCount) {
		this.otherCardCount = otherCardCount;
	}

	@Column(name = "OTHER_CARD_SALES_COUNT", nullable = false)
	public int getOtherCardSalesCount() {
		return this.otherCardSalesCount;
	}

	public void setOtherCardSalesCount(int otherCardSalesCount) {
		this.otherCardSalesCount = otherCardSalesCount;
	}

	@Column(name = "OTHER_CARD_RETURN_COUNT", nullable = false)
	public int getOtherCardReturnCount() {
		return this.otherCardReturnCount;
	}

	public void setOtherCardReturnCount(int otherCardReturnCount) {
		this.otherCardReturnCount = otherCardReturnCount;
	}

	@Column(name = "OTHER_CARD_SALES_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getOtherCardSalesAmount() {
		return this.otherCardSalesAmount;
	}

	public void setOtherCardSalesAmount(long otherCardSalesAmount) {
		this.otherCardSalesAmount = otherCardSalesAmount;
	}

	@Column(name = "OTHER_CARD_RETURN_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getOtherCardReturnAmount() {
		return this.otherCardReturnAmount;
	}

	public void setOtherCardReturnAmount(long otherCardReturnAmount) {
		this.otherCardReturnAmount = otherCardReturnAmount;
	}

	@Column(name = "OTHER_CARD_NET_AMOUNT", nullable = false, precision = 18, scale = 0)
	public long getOtherCardNetAmount() {
		return this.otherCardNetAmount;
	}

	public void setOtherCardNetAmount(long otherCardNetAmount) {
		this.otherCardNetAmount = otherCardNetAmount;
	}

}
