package com.nhatnguyen.pojo;
// Generated Dec 4, 2016 9:17:20 PM by Hibernate Tools 3.6.0.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Merchant generated by hbm2java
 */
@Entity
@Table(name = "MERCHANT")
public class Merchant implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5840980279045961310L;
	private String merchantNumber;
	private Agent agent;
	private Processor processor;
	private String merchantName;
	private String merchantType;
	private String merchantTelephone1;
	private String merchantTelephone2;
	private String merchantTelephone3;
	private String merchantCity;
	private String merchantDistrict;
	private String merchantStreet;
	private String merchantSteetNumber;
	private String merchantRegion;
	private String merchantOwner;
	private String merchantFax;
	private String merchantEmail1;
	private String merchantEmail2;
	private String merchantEmail3;
	private String merchantBankAccount;
	private String merchantStatus;
	private Date merchantAppr0veDate;
	private Date merchantFirstDateActivate;
	private Date merchantLastDayActivate;
	private Set<TransactionDetail> transactionDetails = new HashSet<TransactionDetail>(0);
	private Set<MerchantSummary> merchantSummaries = new HashSet<MerchantSummary>(0);

	public Merchant() {
	}

	public Merchant(String merchantNumber, Processor processor, String merchantName, String merchantType,
			String merchantTelephone1, String merchantCity, String merchantDistrict, String merchantStreet,
			String merchantSteetNumber, String merchantRegion, String merchantOwner, String merchantFax,
			String merchantEmail1, String merchantBankAccount, String merchantStatus, Date merchantAppr0veDate) {
		this.merchantNumber = merchantNumber;
		this.processor = processor;
		this.merchantName = merchantName;
		this.merchantType = merchantType;
		this.merchantTelephone1 = merchantTelephone1;
		this.merchantCity = merchantCity;
		this.merchantDistrict = merchantDistrict;
		this.merchantStreet = merchantStreet;
		this.merchantSteetNumber = merchantSteetNumber;
		this.merchantRegion = merchantRegion;
		this.merchantOwner = merchantOwner;
		this.merchantFax = merchantFax;
		this.merchantEmail1 = merchantEmail1;
		this.merchantBankAccount = merchantBankAccount;
		this.merchantStatus = merchantStatus;
		this.merchantAppr0veDate = merchantAppr0veDate;
	}

	public Merchant(String merchantNumber, Agent agent, Processor processor, String merchantName, String merchantType,
			String merchantTelephone1, String merchantTelephone2, String merchantTelephone3, String merchantCity,
			String merchantDistrict, String merchantStreet, String merchantSteetNumber, String merchantRegion,
			String merchantOwner, String merchantFax, String merchantEmail1, String merchantEmail2,
			String merchantEmail3, String merchantBankAccount, String merchantStatus, Date merchantAppr0veDate,
			Date merchantFirstDateActivate, Date merchantLastDayActivate, Set<TransactionDetail> transactionDetails,
			Set<MerchantSummary> merchantSummaries) {
		this.merchantNumber = merchantNumber;
		this.agent = agent;
		this.processor = processor;
		this.merchantName = merchantName;
		this.merchantType = merchantType;
		this.merchantTelephone1 = merchantTelephone1;
		this.merchantTelephone2 = merchantTelephone2;
		this.merchantTelephone3 = merchantTelephone3;
		this.merchantCity = merchantCity;
		this.merchantDistrict = merchantDistrict;
		this.merchantStreet = merchantStreet;
		this.merchantSteetNumber = merchantSteetNumber;
		this.merchantRegion = merchantRegion;
		this.merchantOwner = merchantOwner;
		this.merchantFax = merchantFax;
		this.merchantEmail1 = merchantEmail1;
		this.merchantEmail2 = merchantEmail2;
		this.merchantEmail3 = merchantEmail3;
		this.merchantBankAccount = merchantBankAccount;
		this.merchantStatus = merchantStatus;
		this.merchantAppr0veDate = merchantAppr0veDate;
		this.merchantFirstDateActivate = merchantFirstDateActivate;
		this.merchantLastDayActivate = merchantLastDayActivate;
		this.transactionDetails = transactionDetails;
		this.merchantSummaries = merchantSummaries;
	}

	@Id

	@Column(name = "MERCHANT_NUMBER", unique = true, nullable = false)
	public String getMerchantNumber() {
		return this.merchantNumber;
	}

	public void setMerchantNumber(String merchantNumber) {
		this.merchantNumber = merchantNumber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANAGE_AGENT")
	public Agent getAgent() {
		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BACKEND_PROCESSOR", nullable = false)
	public Processor getProcessor() {
		return this.processor;
	}

	public void setProcessor(Processor processor) {
		this.processor = processor;
	}

	@Column(name = "MERCHANT_NAME", nullable = false)
	public String getMerchantName() {
		return this.merchantName;
	}

	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	@Column(name = "MERCHANT_TYPE", nullable = false)
	public String getMerchantType() {
		return this.merchantType;
	}

	public void setMerchantType(String merchantType) {
		this.merchantType = merchantType;
	}

	@Column(name = "MERCHANT_TELEPHONE1", nullable = false)
	public String getMerchantTelephone1() {
		return this.merchantTelephone1;
	}

	public void setMerchantTelephone1(String merchantTelephone1) {
		this.merchantTelephone1 = merchantTelephone1;
	}

	@Column(name = "MERCHANT_TELEPHONE2")
	public String getMerchantTelephone2() {
		return this.merchantTelephone2;
	}

	public void setMerchantTelephone2(String merchantTelephone2) {
		this.merchantTelephone2 = merchantTelephone2;
	}

	@Column(name = "MERCHANT_TELEPHONE3")
	public String getMerchantTelephone3() {
		return this.merchantTelephone3;
	}

	public void setMerchantTelephone3(String merchantTelephone3) {
		this.merchantTelephone3 = merchantTelephone3;
	}

	@Column(name = "MERCHANT_CITY", nullable = false)
	public String getMerchantCity() {
		return this.merchantCity;
	}

	public void setMerchantCity(String merchantCity) {
		this.merchantCity = merchantCity;
	}

	@Column(name = "MERCHANT_DISTRICT", nullable = false)
	public String getMerchantDistrict() {
		return this.merchantDistrict;
	}

	public void setMerchantDistrict(String merchantDistrict) {
		this.merchantDistrict = merchantDistrict;
	}

	@Column(name = "MERCHANT_STREET", nullable = false)
	public String getMerchantStreet() {
		return this.merchantStreet;
	}

	public void setMerchantStreet(String merchantStreet) {
		this.merchantStreet = merchantStreet;
	}

	@Column(name = "MERCHANT_STEET_NUMBER", nullable = false)
	public String getMerchantSteetNumber() {
		return this.merchantSteetNumber;
	}

	public void setMerchantSteetNumber(String merchantSteetNumber) {
		this.merchantSteetNumber = merchantSteetNumber;
	}

	@Column(name = "MERCHANT_REGION", nullable = false)
	public String getMerchantRegion() {
		return this.merchantRegion;
	}

	public void setMerchantRegion(String merchantRegion) {
		this.merchantRegion = merchantRegion;
	}

	@Column(name = "MERCHANT_OWNER", nullable = false)
	public String getMerchantOwner() {
		return this.merchantOwner;
	}

	public void setMerchantOwner(String merchantOwner) {
		this.merchantOwner = merchantOwner;
	}

	@Column(name = "MERCHANT_FAX", nullable = false)
	public String getMerchantFax() {
		return this.merchantFax;
	}

	public void setMerchantFax(String merchantFax) {
		this.merchantFax = merchantFax;
	}

	@Column(name = "MERCHANT_EMAIL1", nullable = false)
	public String getMerchantEmail1() {
		return this.merchantEmail1;
	}

	public void setMerchantEmail1(String merchantEmail1) {
		this.merchantEmail1 = merchantEmail1;
	}

	@Column(name = "MERCHANT_EMAIL2")
	public String getMerchantEmail2() {
		return this.merchantEmail2;
	}

	public void setMerchantEmail2(String merchantEmail2) {
		this.merchantEmail2 = merchantEmail2;
	}

	@Column(name = "MERCHANT_EMAIL3")
	public String getMerchantEmail3() {
		return this.merchantEmail3;
	}

	public void setMerchantEmail3(String merchantEmail3) {
		this.merchantEmail3 = merchantEmail3;
	}

	@Column(name = "MERCHANT_BANK_ACCOUNT", nullable = false)
	public String getMerchantBankAccount() {
		return this.merchantBankAccount;
	}

	public void setMerchantBankAccount(String merchantBankAccount) {
		this.merchantBankAccount = merchantBankAccount;
	}

	@Column(name = "MERCHANT_STATUS", nullable = false)
	public String getMerchantStatus() {
		return this.merchantStatus;
	}

	public void setMerchantStatus(String merchantStatus) {
		this.merchantStatus = merchantStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MERCHANT_APPR0VE_DATE", nullable = false, length = 23)
	public Date getMerchantAppr0veDate() {
		return this.merchantAppr0veDate;
	}

	public void setMerchantAppr0veDate(Date merchantAppr0veDate) {
		this.merchantAppr0veDate = merchantAppr0veDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MERCHANT_FIRST_DATE_ACTIVATE", length = 23)
	public Date getMerchantFirstDateActivate() {
		return this.merchantFirstDateActivate;
	}

	public void setMerchantFirstDateActivate(Date merchantFirstDateActivate) {
		this.merchantFirstDateActivate = merchantFirstDateActivate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MERCHANT_LAST_DAY_ACTIVATE", length = 23)
	public Date getMerchantLastDayActivate() {
		return this.merchantLastDayActivate;
	}

	public void setMerchantLastDayActivate(Date merchantLastDayActivate) {
		this.merchantLastDayActivate = merchantLastDayActivate;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<TransactionDetail> getTransactionDetails() {
		return this.transactionDetails;
	}

	public void setTransactionDetails(Set<TransactionDetail> transactionDetails) {
		this.transactionDetails = transactionDetails;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
	public Set<MerchantSummary> getMerchantSummaries() {
		return this.merchantSummaries;
	}

	public void setMerchantSummaries(Set<MerchantSummary> merchantSummaries) {
		this.merchantSummaries = merchantSummaries;
	}

}
