package com.nhatnguyen.pojo;
// Generated Dec 4, 2016 9:17:20 PM by Hibernate Tools 3.6.0.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Retrival generated by hbm2java
 */
@Entity
@Table(name = "RETRIVAL")
public class Retrival implements Serializable {

	private String retrivalId;
	private String transactionId;
	private Date retrivalDate;
	private String retrivalDescription;

	public Retrival() {
	}

	public Retrival(String retrivalId, Date retrivalDate) {
		this.retrivalId = retrivalId;
		this.retrivalDate = retrivalDate;
	}

	public Retrival(String retrivalId, String transactionId, Date retrivalDate, String retrivalDescription) {
		this.retrivalId = retrivalId;
		this.transactionId = transactionId;
		this.retrivalDate = retrivalDate;
		this.retrivalDescription = retrivalDescription;
	}

	@Id

	@Column(name = "RETRIVAL_ID", unique = true, nullable = false)
	public String getRetrivalId() {
		return this.retrivalId;
	}

	public void setRetrivalId(String retrivalId) {
		this.retrivalId = retrivalId;
	}

	@Column(name = "TRANSACTION_ID")
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RETRIVAL_DATE", nullable = false, length = 23)
	public Date getRetrivalDate() {
		return this.retrivalDate;
	}

	public void setRetrivalDate(Date retrivalDate) {
		this.retrivalDate = retrivalDate;
	}

	@Column(name = "RETRIVAL_DESCRIPTION")
	public String getRetrivalDescription() {
		return this.retrivalDescription;
	}

	public void setRetrivalDescription(String retrivalDescription) {
		this.retrivalDescription = retrivalDescription;
	}

}
