//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DOANPTUDHDEntities : DbContext
    {
        public DOANPTUDHDEntities()
            : base("name=DOANPTUDHDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNT { get; set; }
        public virtual DbSet<AGENT> AGENT { get; set; }
        public virtual DbSet<MERCHANT> MERCHANT { get; set; }
        public virtual DbSet<MERCHANT_SUMMARY> MERCHANT_SUMMARY { get; set; }
        public virtual DbSet<MERCHANT_SUMMARY_MONTH> MERCHANT_SUMMARY_MONTH { get; set; }
        public virtual DbSet<MERCHANT_SUMMARY_QUARTER> MERCHANT_SUMMARY_QUARTER { get; set; }
        public virtual DbSet<MERCHANT_SUMMARY_YEAR> MERCHANT_SUMMARY_YEAR { get; set; }
        public virtual DbSet<MESSAGE> MESSAGE { get; set; }
        public virtual DbSet<MESSAGE_OUTBOX> MESSAGE_OUTBOX { get; set; }
        public virtual DbSet<PROCESSOR> PROCESSOR { get; set; }
        public virtual DbSet<RETRIVAL> RETRIVAL { get; set; }
        public virtual DbSet<TRANSACTION_DETAIL> TRANSACTION_DETAIL { get; set; }
    
        public virtual int insert_MERCHANT_SUMMARY(string mERCHANT_NUMBER, Nullable<System.DateTime> rEPORT_DATE)
        {
            var mERCHANT_NUMBERParameter = mERCHANT_NUMBER != null ?
                new ObjectParameter("MERCHANT_NUMBER", mERCHANT_NUMBER) :
                new ObjectParameter("MERCHANT_NUMBER", typeof(string));
    
            var rEPORT_DATEParameter = rEPORT_DATE.HasValue ?
                new ObjectParameter("REPORT_DATE", rEPORT_DATE) :
                new ObjectParameter("REPORT_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_MERCHANT_SUMMARY", mERCHANT_NUMBERParameter, rEPORT_DATEParameter);
        }
    
        public virtual int Sp_ActDeactAgent(string agentNumber)
        {
            var agentNumberParameter = agentNumber != null ?
                new ObjectParameter("agentNumber", agentNumber) :
                new ObjectParameter("agentNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_ActDeactAgent", agentNumberParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_CountUnreadMessage(string receiver)
        {
            var receiverParameter = receiver != null ?
                new ObjectParameter("receiver", receiver) :
                new ObjectParameter("receiver", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_CountUnreadMessage", receiverParameter);
        }
    
        public virtual int Sp_DeleteMessage(string idMessages)
        {
            var idMessagesParameter = idMessages != null ?
                new ObjectParameter("idMessages", idMessages) :
                new ObjectParameter("idMessages", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_DeleteMessage", idMessagesParameter);
        }
    
        public virtual int Sp_DeleteMessageOutbox(string idMessages)
        {
            var idMessagesParameter = idMessages != null ?
                new ObjectParameter("idMessages", idMessages) :
                new ObjectParameter("idMessages", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_DeleteMessageOutbox", idMessagesParameter);
        }
    
        public virtual int Sp_InsertAgent(string aGENT_NUMBER, string aGENT_NAME, string aGENT_TELEPHONE1, string aGENT_TELEPHONE2, string aGENT_TELEPHONE3, string aGENT_CITY, string aGENT_DISTRICT, string aGENT_STREET, string aGENT_STREET_NUMBER, string aGENT_REGION, string aGENT_OWNER, string aGENT_FAX, string aGENT_EMAIL_1, string aGENT_EMAIL_2, string aGENT_EMAIL_3, string aGENT_BANK_ACCOUNT, string bACKEND_PROCESSOR, string aGENT_STATUS, Nullable<System.DateTime> aGENT_APPR0VE_DATE, Nullable<System.DateTime> aGENT_FIRST_DATE_ACTIVATE)
        {
            var aGENT_NUMBERParameter = aGENT_NUMBER != null ?
                new ObjectParameter("AGENT_NUMBER", aGENT_NUMBER) :
                new ObjectParameter("AGENT_NUMBER", typeof(string));
    
            var aGENT_NAMEParameter = aGENT_NAME != null ?
                new ObjectParameter("AGENT_NAME", aGENT_NAME) :
                new ObjectParameter("AGENT_NAME", typeof(string));
    
            var aGENT_TELEPHONE1Parameter = aGENT_TELEPHONE1 != null ?
                new ObjectParameter("AGENT_TELEPHONE1", aGENT_TELEPHONE1) :
                new ObjectParameter("AGENT_TELEPHONE1", typeof(string));
    
            var aGENT_TELEPHONE2Parameter = aGENT_TELEPHONE2 != null ?
                new ObjectParameter("AGENT_TELEPHONE2", aGENT_TELEPHONE2) :
                new ObjectParameter("AGENT_TELEPHONE2", typeof(string));
    
            var aGENT_TELEPHONE3Parameter = aGENT_TELEPHONE3 != null ?
                new ObjectParameter("AGENT_TELEPHONE3", aGENT_TELEPHONE3) :
                new ObjectParameter("AGENT_TELEPHONE3", typeof(string));
    
            var aGENT_CITYParameter = aGENT_CITY != null ?
                new ObjectParameter("AGENT_CITY", aGENT_CITY) :
                new ObjectParameter("AGENT_CITY", typeof(string));
    
            var aGENT_DISTRICTParameter = aGENT_DISTRICT != null ?
                new ObjectParameter("AGENT_DISTRICT", aGENT_DISTRICT) :
                new ObjectParameter("AGENT_DISTRICT", typeof(string));
    
            var aGENT_STREETParameter = aGENT_STREET != null ?
                new ObjectParameter("AGENT_STREET", aGENT_STREET) :
                new ObjectParameter("AGENT_STREET", typeof(string));
    
            var aGENT_STREET_NUMBERParameter = aGENT_STREET_NUMBER != null ?
                new ObjectParameter("AGENT_STREET_NUMBER", aGENT_STREET_NUMBER) :
                new ObjectParameter("AGENT_STREET_NUMBER", typeof(string));
    
            var aGENT_REGIONParameter = aGENT_REGION != null ?
                new ObjectParameter("AGENT_REGION", aGENT_REGION) :
                new ObjectParameter("AGENT_REGION", typeof(string));
    
            var aGENT_OWNERParameter = aGENT_OWNER != null ?
                new ObjectParameter("AGENT_OWNER", aGENT_OWNER) :
                new ObjectParameter("AGENT_OWNER", typeof(string));
    
            var aGENT_FAXParameter = aGENT_FAX != null ?
                new ObjectParameter("AGENT_FAX", aGENT_FAX) :
                new ObjectParameter("AGENT_FAX", typeof(string));
    
            var aGENT_EMAIL_1Parameter = aGENT_EMAIL_1 != null ?
                new ObjectParameter("AGENT_EMAIL_1", aGENT_EMAIL_1) :
                new ObjectParameter("AGENT_EMAIL_1", typeof(string));
    
            var aGENT_EMAIL_2Parameter = aGENT_EMAIL_2 != null ?
                new ObjectParameter("AGENT_EMAIL_2", aGENT_EMAIL_2) :
                new ObjectParameter("AGENT_EMAIL_2", typeof(string));
    
            var aGENT_EMAIL_3Parameter = aGENT_EMAIL_3 != null ?
                new ObjectParameter("AGENT_EMAIL_3", aGENT_EMAIL_3) :
                new ObjectParameter("AGENT_EMAIL_3", typeof(string));
    
            var aGENT_BANK_ACCOUNTParameter = aGENT_BANK_ACCOUNT != null ?
                new ObjectParameter("AGENT_BANK_ACCOUNT", aGENT_BANK_ACCOUNT) :
                new ObjectParameter("AGENT_BANK_ACCOUNT", typeof(string));
    
            var bACKEND_PROCESSORParameter = bACKEND_PROCESSOR != null ?
                new ObjectParameter("BACKEND_PROCESSOR", bACKEND_PROCESSOR) :
                new ObjectParameter("BACKEND_PROCESSOR", typeof(string));
    
            var aGENT_STATUSParameter = aGENT_STATUS != null ?
                new ObjectParameter("AGENT_STATUS", aGENT_STATUS) :
                new ObjectParameter("AGENT_STATUS", typeof(string));
    
            var aGENT_APPR0VE_DATEParameter = aGENT_APPR0VE_DATE.HasValue ?
                new ObjectParameter("AGENT_APPR0VE_DATE", aGENT_APPR0VE_DATE) :
                new ObjectParameter("AGENT_APPR0VE_DATE", typeof(System.DateTime));
    
            var aGENT_FIRST_DATE_ACTIVATEParameter = aGENT_FIRST_DATE_ACTIVATE.HasValue ?
                new ObjectParameter("AGENT_FIRST_DATE_ACTIVATE", aGENT_FIRST_DATE_ACTIVATE) :
                new ObjectParameter("AGENT_FIRST_DATE_ACTIVATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_InsertAgent", aGENT_NUMBERParameter, aGENT_NAMEParameter, aGENT_TELEPHONE1Parameter, aGENT_TELEPHONE2Parameter, aGENT_TELEPHONE3Parameter, aGENT_CITYParameter, aGENT_DISTRICTParameter, aGENT_STREETParameter, aGENT_STREET_NUMBERParameter, aGENT_REGIONParameter, aGENT_OWNERParameter, aGENT_FAXParameter, aGENT_EMAIL_1Parameter, aGENT_EMAIL_2Parameter, aGENT_EMAIL_3Parameter, aGENT_BANK_ACCOUNTParameter, bACKEND_PROCESSORParameter, aGENT_STATUSParameter, aGENT_APPR0VE_DATEParameter, aGENT_FIRST_DATE_ACTIVATEParameter);
        }
    
        public virtual int Sp_InsertMerchant(string mERCHANT_NUMBER, string mERCHANT_NAME, string mERCHANT_TYPE, string mERCHANT_TELEPHONE1, string mERCHANT_TELEPHONE2, string mERCHANT_TELEPHONE3, string mERCHANT_CITY, string mERCHANT_DISTRICT, string mERCHANT_STREET, string mERCHANT_STREET_NUMBER, string mERCHANT_REGION, string mERCHANT_OWNER, string mERCHANT_FAX, string mERCHANT_EMAIL1, string mERCHANT_EMAIL2, string mERCHANT_EMAIL3, string mERCHANT_BANK_ACCOUNT, string mANAGE_AGENT, string bACKEND_PROCESSOR, string mERCHANT_STATUS, Nullable<System.DateTime> mERCHANT_APPR0VE_DATE, Nullable<System.DateTime> mERCHANT_FIRST_DATE_ACTIVATE)
        {
            var mERCHANT_NUMBERParameter = mERCHANT_NUMBER != null ?
                new ObjectParameter("MERCHANT_NUMBER", mERCHANT_NUMBER) :
                new ObjectParameter("MERCHANT_NUMBER", typeof(string));
    
            var mERCHANT_NAMEParameter = mERCHANT_NAME != null ?
                new ObjectParameter("MERCHANT_NAME", mERCHANT_NAME) :
                new ObjectParameter("MERCHANT_NAME", typeof(string));
    
            var mERCHANT_TYPEParameter = mERCHANT_TYPE != null ?
                new ObjectParameter("MERCHANT_TYPE", mERCHANT_TYPE) :
                new ObjectParameter("MERCHANT_TYPE", typeof(string));
    
            var mERCHANT_TELEPHONE1Parameter = mERCHANT_TELEPHONE1 != null ?
                new ObjectParameter("MERCHANT_TELEPHONE1", mERCHANT_TELEPHONE1) :
                new ObjectParameter("MERCHANT_TELEPHONE1", typeof(string));
    
            var mERCHANT_TELEPHONE2Parameter = mERCHANT_TELEPHONE2 != null ?
                new ObjectParameter("MERCHANT_TELEPHONE2", mERCHANT_TELEPHONE2) :
                new ObjectParameter("MERCHANT_TELEPHONE2", typeof(string));
    
            var mERCHANT_TELEPHONE3Parameter = mERCHANT_TELEPHONE3 != null ?
                new ObjectParameter("MERCHANT_TELEPHONE3", mERCHANT_TELEPHONE3) :
                new ObjectParameter("MERCHANT_TELEPHONE3", typeof(string));
    
            var mERCHANT_CITYParameter = mERCHANT_CITY != null ?
                new ObjectParameter("MERCHANT_CITY", mERCHANT_CITY) :
                new ObjectParameter("MERCHANT_CITY", typeof(string));
    
            var mERCHANT_DISTRICTParameter = mERCHANT_DISTRICT != null ?
                new ObjectParameter("MERCHANT_DISTRICT", mERCHANT_DISTRICT) :
                new ObjectParameter("MERCHANT_DISTRICT", typeof(string));
    
            var mERCHANT_STREETParameter = mERCHANT_STREET != null ?
                new ObjectParameter("MERCHANT_STREET", mERCHANT_STREET) :
                new ObjectParameter("MERCHANT_STREET", typeof(string));
    
            var mERCHANT_STREET_NUMBERParameter = mERCHANT_STREET_NUMBER != null ?
                new ObjectParameter("MERCHANT_STREET_NUMBER", mERCHANT_STREET_NUMBER) :
                new ObjectParameter("MERCHANT_STREET_NUMBER", typeof(string));
    
            var mERCHANT_REGIONParameter = mERCHANT_REGION != null ?
                new ObjectParameter("MERCHANT_REGION", mERCHANT_REGION) :
                new ObjectParameter("MERCHANT_REGION", typeof(string));
    
            var mERCHANT_OWNERParameter = mERCHANT_OWNER != null ?
                new ObjectParameter("MERCHANT_OWNER", mERCHANT_OWNER) :
                new ObjectParameter("MERCHANT_OWNER", typeof(string));
    
            var mERCHANT_FAXParameter = mERCHANT_FAX != null ?
                new ObjectParameter("MERCHANT_FAX", mERCHANT_FAX) :
                new ObjectParameter("MERCHANT_FAX", typeof(string));
    
            var mERCHANT_EMAIL1Parameter = mERCHANT_EMAIL1 != null ?
                new ObjectParameter("MERCHANT_EMAIL1", mERCHANT_EMAIL1) :
                new ObjectParameter("MERCHANT_EMAIL1", typeof(string));
    
            var mERCHANT_EMAIL2Parameter = mERCHANT_EMAIL2 != null ?
                new ObjectParameter("MERCHANT_EMAIL2", mERCHANT_EMAIL2) :
                new ObjectParameter("MERCHANT_EMAIL2", typeof(string));
    
            var mERCHANT_EMAIL3Parameter = mERCHANT_EMAIL3 != null ?
                new ObjectParameter("MERCHANT_EMAIL3", mERCHANT_EMAIL3) :
                new ObjectParameter("MERCHANT_EMAIL3", typeof(string));
    
            var mERCHANT_BANK_ACCOUNTParameter = mERCHANT_BANK_ACCOUNT != null ?
                new ObjectParameter("MERCHANT_BANK_ACCOUNT", mERCHANT_BANK_ACCOUNT) :
                new ObjectParameter("MERCHANT_BANK_ACCOUNT", typeof(string));
    
            var mANAGE_AGENTParameter = mANAGE_AGENT != null ?
                new ObjectParameter("MANAGE_AGENT", mANAGE_AGENT) :
                new ObjectParameter("MANAGE_AGENT", typeof(string));
    
            var bACKEND_PROCESSORParameter = bACKEND_PROCESSOR != null ?
                new ObjectParameter("BACKEND_PROCESSOR", bACKEND_PROCESSOR) :
                new ObjectParameter("BACKEND_PROCESSOR", typeof(string));
    
            var mERCHANT_STATUSParameter = mERCHANT_STATUS != null ?
                new ObjectParameter("MERCHANT_STATUS", mERCHANT_STATUS) :
                new ObjectParameter("MERCHANT_STATUS", typeof(string));
    
            var mERCHANT_APPR0VE_DATEParameter = mERCHANT_APPR0VE_DATE.HasValue ?
                new ObjectParameter("MERCHANT_APPR0VE_DATE", mERCHANT_APPR0VE_DATE) :
                new ObjectParameter("MERCHANT_APPR0VE_DATE", typeof(System.DateTime));
    
            var mERCHANT_FIRST_DATE_ACTIVATEParameter = mERCHANT_FIRST_DATE_ACTIVATE.HasValue ?
                new ObjectParameter("MERCHANT_FIRST_DATE_ACTIVATE", mERCHANT_FIRST_DATE_ACTIVATE) :
                new ObjectParameter("MERCHANT_FIRST_DATE_ACTIVATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_InsertMerchant", mERCHANT_NUMBERParameter, mERCHANT_NAMEParameter, mERCHANT_TYPEParameter, mERCHANT_TELEPHONE1Parameter, mERCHANT_TELEPHONE2Parameter, mERCHANT_TELEPHONE3Parameter, mERCHANT_CITYParameter, mERCHANT_DISTRICTParameter, mERCHANT_STREETParameter, mERCHANT_STREET_NUMBERParameter, mERCHANT_REGIONParameter, mERCHANT_OWNERParameter, mERCHANT_FAXParameter, mERCHANT_EMAIL1Parameter, mERCHANT_EMAIL2Parameter, mERCHANT_EMAIL3Parameter, mERCHANT_BANK_ACCOUNTParameter, mANAGE_AGENTParameter, bACKEND_PROCESSORParameter, mERCHANT_STATUSParameter, mERCHANT_APPR0VE_DATEParameter, mERCHANT_FIRST_DATE_ACTIVATEParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_KTInsertAgent(string backend_processor, string agent_number)
        {
            var backend_processorParameter = backend_processor != null ?
                new ObjectParameter("backend_processor", backend_processor) :
                new ObjectParameter("backend_processor", typeof(string));
    
            var agent_numberParameter = agent_number != null ?
                new ObjectParameter("agent_number", agent_number) :
                new ObjectParameter("agent_number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_KTInsertAgent", backend_processorParameter, agent_numberParameter);
        }
    
        public virtual ObjectResult<Sp_LoadMerchantNoAgent_Result> Sp_LoadMerchantNoAgent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_LoadMerchantNoAgent_Result>("Sp_LoadMerchantNoAgent");
        }
    
        public virtual ObjectResult<Sp_LoadMerchantOfAgent_Result> Sp_LoadMerchantOfAgent(string agent)
        {
            var agentParameter = agent != null ?
                new ObjectParameter("agent", agent) :
                new ObjectParameter("agent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_LoadMerchantOfAgent_Result>("Sp_LoadMerchantOfAgent", agentParameter);
        }
    
        public virtual ObjectResult<Sp_LoadMerchantOtherAgent_Result> Sp_LoadMerchantOtherAgent(string agent)
        {
            var agentParameter = agent != null ?
                new ObjectParameter("agent", agent) :
                new ObjectParameter("agent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_LoadMerchantOtherAgent_Result>("Sp_LoadMerchantOtherAgent", agentParameter);
        }
    
        public virtual ObjectResult<Sp_LoginUser_Result> Sp_LoginUser(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_LoginUser_Result>("Sp_LoginUser", usernameParameter, passwordParameter);
        }
    
        public virtual int Sp_RemoveAgentOfMerchant(string merchant)
        {
            var merchantParameter = merchant != null ?
                new ObjectParameter("merchant", merchant) :
                new ObjectParameter("merchant", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_RemoveAgentOfMerchant", merchantParameter);
        }
    
        public virtual ObjectResult<SP_RETRIVAL_Result> SP_RETRIVAL(string rETRIVAL_ID, Nullable<System.DateTime> rETRIVAL_DATE)
        {
            var rETRIVAL_IDParameter = rETRIVAL_ID != null ?
                new ObjectParameter("RETRIVAL_ID", rETRIVAL_ID) :
                new ObjectParameter("RETRIVAL_ID", typeof(string));
    
            var rETRIVAL_DATEParameter = rETRIVAL_DATE.HasValue ?
                new ObjectParameter("RETRIVAL_DATE", rETRIVAL_DATE) :
                new ObjectParameter("RETRIVAL_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RETRIVAL_Result>("SP_RETRIVAL", rETRIVAL_IDParameter, rETRIVAL_DATEParameter);
        }
    
        public virtual ObjectResult<Sp_SearchMerchant_Result> Sp_SearchMerchant(string num, string name, string type, string agent, string city)
        {
            var numParameter = num != null ?
                new ObjectParameter("num", num) :
                new ObjectParameter("num", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var agentParameter = agent != null ?
                new ObjectParameter("agent", agent) :
                new ObjectParameter("agent", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_SearchMerchant_Result>("Sp_SearchMerchant", numParameter, nameParameter, typeParameter, agentParameter, cityParameter);
        }
    
        public virtual ObjectResult<Sp_ShowInbox_Result> Sp_ShowInbox(string receiver)
        {
            var receiverParameter = receiver != null ?
                new ObjectParameter("receiver", receiver) :
                new ObjectParameter("receiver", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ShowInbox_Result>("Sp_ShowInbox", receiverParameter);
        }
    
        public virtual ObjectResult<Sp_ShowOutbox_Result> Sp_ShowOutbox(string sender)
        {
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ShowOutbox_Result>("Sp_ShowOutbox", senderParameter);
        }
    
        public virtual int Sp_UpdateAgent(string aGENT_NUMBER, string aGENT_NAME, string aGENT_TELEPHONE1, string aGENT_TELEPHONE2, string aGENT_TELEPHONE3, string aGENT_CITY, string aGENT_DISTRICT, string aGENT_STREET, string aGENT_SRTEET_NUMBER, string aGENT_REGION, string aGENT_OWNER, string aGENT_FAX, string aGENT_EMAIL_1, string aGENT_EMAIL_2, string aGENT_EMAIL_3, string aGENT_BANK_ACCOUNT)
        {
            var aGENT_NUMBERParameter = aGENT_NUMBER != null ?
                new ObjectParameter("AGENT_NUMBER", aGENT_NUMBER) :
                new ObjectParameter("AGENT_NUMBER", typeof(string));
    
            var aGENT_NAMEParameter = aGENT_NAME != null ?
                new ObjectParameter("AGENT_NAME", aGENT_NAME) :
                new ObjectParameter("AGENT_NAME", typeof(string));
    
            var aGENT_TELEPHONE1Parameter = aGENT_TELEPHONE1 != null ?
                new ObjectParameter("AGENT_TELEPHONE1", aGENT_TELEPHONE1) :
                new ObjectParameter("AGENT_TELEPHONE1", typeof(string));
    
            var aGENT_TELEPHONE2Parameter = aGENT_TELEPHONE2 != null ?
                new ObjectParameter("AGENT_TELEPHONE2", aGENT_TELEPHONE2) :
                new ObjectParameter("AGENT_TELEPHONE2", typeof(string));
    
            var aGENT_TELEPHONE3Parameter = aGENT_TELEPHONE3 != null ?
                new ObjectParameter("AGENT_TELEPHONE3", aGENT_TELEPHONE3) :
                new ObjectParameter("AGENT_TELEPHONE3", typeof(string));
    
            var aGENT_CITYParameter = aGENT_CITY != null ?
                new ObjectParameter("AGENT_CITY", aGENT_CITY) :
                new ObjectParameter("AGENT_CITY", typeof(string));
    
            var aGENT_DISTRICTParameter = aGENT_DISTRICT != null ?
                new ObjectParameter("AGENT_DISTRICT", aGENT_DISTRICT) :
                new ObjectParameter("AGENT_DISTRICT", typeof(string));
    
            var aGENT_STREETParameter = aGENT_STREET != null ?
                new ObjectParameter("AGENT_STREET", aGENT_STREET) :
                new ObjectParameter("AGENT_STREET", typeof(string));
    
            var aGENT_SRTEET_NUMBERParameter = aGENT_SRTEET_NUMBER != null ?
                new ObjectParameter("AGENT_SRTEET_NUMBER", aGENT_SRTEET_NUMBER) :
                new ObjectParameter("AGENT_SRTEET_NUMBER", typeof(string));
    
            var aGENT_REGIONParameter = aGENT_REGION != null ?
                new ObjectParameter("AGENT_REGION", aGENT_REGION) :
                new ObjectParameter("AGENT_REGION", typeof(string));
    
            var aGENT_OWNERParameter = aGENT_OWNER != null ?
                new ObjectParameter("AGENT_OWNER", aGENT_OWNER) :
                new ObjectParameter("AGENT_OWNER", typeof(string));
    
            var aGENT_FAXParameter = aGENT_FAX != null ?
                new ObjectParameter("AGENT_FAX", aGENT_FAX) :
                new ObjectParameter("AGENT_FAX", typeof(string));
    
            var aGENT_EMAIL_1Parameter = aGENT_EMAIL_1 != null ?
                new ObjectParameter("AGENT_EMAIL_1", aGENT_EMAIL_1) :
                new ObjectParameter("AGENT_EMAIL_1", typeof(string));
    
            var aGENT_EMAIL_2Parameter = aGENT_EMAIL_2 != null ?
                new ObjectParameter("AGENT_EMAIL_2", aGENT_EMAIL_2) :
                new ObjectParameter("AGENT_EMAIL_2", typeof(string));
    
            var aGENT_EMAIL_3Parameter = aGENT_EMAIL_3 != null ?
                new ObjectParameter("AGENT_EMAIL_3", aGENT_EMAIL_3) :
                new ObjectParameter("AGENT_EMAIL_3", typeof(string));
    
            var aGENT_BANK_ACCOUNTParameter = aGENT_BANK_ACCOUNT != null ?
                new ObjectParameter("AGENT_BANK_ACCOUNT", aGENT_BANK_ACCOUNT) :
                new ObjectParameter("AGENT_BANK_ACCOUNT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UpdateAgent", aGENT_NUMBERParameter, aGENT_NAMEParameter, aGENT_TELEPHONE1Parameter, aGENT_TELEPHONE2Parameter, aGENT_TELEPHONE3Parameter, aGENT_CITYParameter, aGENT_DISTRICTParameter, aGENT_STREETParameter, aGENT_SRTEET_NUMBERParameter, aGENT_REGIONParameter, aGENT_OWNERParameter, aGENT_FAXParameter, aGENT_EMAIL_1Parameter, aGENT_EMAIL_2Parameter, aGENT_EMAIL_3Parameter, aGENT_BANK_ACCOUNTParameter);
        }
    
        public virtual int Sp_UpdateAgentOfMerchant(string merchant, string agent)
        {
            var merchantParameter = merchant != null ?
                new ObjectParameter("merchant", merchant) :
                new ObjectParameter("merchant", typeof(string));
    
            var agentParameter = agent != null ?
                new ObjectParameter("agent", agent) :
                new ObjectParameter("agent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UpdateAgentOfMerchant", merchantParameter, agentParameter);
        }
    
        public virtual int Sp_UpdateMerchant(string mERCHANT_NUMBER, string mERCHANT_NAME, string mERCHANT_TYPE, string mERCHANT_TELEPHONE1, string mERCHANT_TELEPHONE2, string mERCHANT_TELEPHONE3, string mERCHANT_CITY, string mERCHANT_DISTRICT, string mERCHANT_STREET, string mERCHANT_STEET_NUMBER, string mERCHANT_REGION, string mERCHANT_OWNER, string mERCHANT_FAX, string mERCHANT_EMAIL1, string mERCHANT_EMAIL2, string mERCHANT_EMAIL3, string mERCHANT_BANK_ACCOUNT, Nullable<System.DateTime> mERCHANT_LAST_DAY_ACTIVATE)
        {
            var mERCHANT_NUMBERParameter = mERCHANT_NUMBER != null ?
                new ObjectParameter("MERCHANT_NUMBER", mERCHANT_NUMBER) :
                new ObjectParameter("MERCHANT_NUMBER", typeof(string));
    
            var mERCHANT_NAMEParameter = mERCHANT_NAME != null ?
                new ObjectParameter("MERCHANT_NAME", mERCHANT_NAME) :
                new ObjectParameter("MERCHANT_NAME", typeof(string));
    
            var mERCHANT_TYPEParameter = mERCHANT_TYPE != null ?
                new ObjectParameter("MERCHANT_TYPE", mERCHANT_TYPE) :
                new ObjectParameter("MERCHANT_TYPE", typeof(string));
    
            var mERCHANT_TELEPHONE1Parameter = mERCHANT_TELEPHONE1 != null ?
                new ObjectParameter("MERCHANT_TELEPHONE1", mERCHANT_TELEPHONE1) :
                new ObjectParameter("MERCHANT_TELEPHONE1", typeof(string));
    
            var mERCHANT_TELEPHONE2Parameter = mERCHANT_TELEPHONE2 != null ?
                new ObjectParameter("MERCHANT_TELEPHONE2", mERCHANT_TELEPHONE2) :
                new ObjectParameter("MERCHANT_TELEPHONE2", typeof(string));
    
            var mERCHANT_TELEPHONE3Parameter = mERCHANT_TELEPHONE3 != null ?
                new ObjectParameter("MERCHANT_TELEPHONE3", mERCHANT_TELEPHONE3) :
                new ObjectParameter("MERCHANT_TELEPHONE3", typeof(string));
    
            var mERCHANT_CITYParameter = mERCHANT_CITY != null ?
                new ObjectParameter("MERCHANT_CITY", mERCHANT_CITY) :
                new ObjectParameter("MERCHANT_CITY", typeof(string));
    
            var mERCHANT_DISTRICTParameter = mERCHANT_DISTRICT != null ?
                new ObjectParameter("MERCHANT_DISTRICT", mERCHANT_DISTRICT) :
                new ObjectParameter("MERCHANT_DISTRICT", typeof(string));
    
            var mERCHANT_STREETParameter = mERCHANT_STREET != null ?
                new ObjectParameter("MERCHANT_STREET", mERCHANT_STREET) :
                new ObjectParameter("MERCHANT_STREET", typeof(string));
    
            var mERCHANT_STEET_NUMBERParameter = mERCHANT_STEET_NUMBER != null ?
                new ObjectParameter("MERCHANT_STEET_NUMBER", mERCHANT_STEET_NUMBER) :
                new ObjectParameter("MERCHANT_STEET_NUMBER", typeof(string));
    
            var mERCHANT_REGIONParameter = mERCHANT_REGION != null ?
                new ObjectParameter("MERCHANT_REGION", mERCHANT_REGION) :
                new ObjectParameter("MERCHANT_REGION", typeof(string));
    
            var mERCHANT_OWNERParameter = mERCHANT_OWNER != null ?
                new ObjectParameter("MERCHANT_OWNER", mERCHANT_OWNER) :
                new ObjectParameter("MERCHANT_OWNER", typeof(string));
    
            var mERCHANT_FAXParameter = mERCHANT_FAX != null ?
                new ObjectParameter("MERCHANT_FAX", mERCHANT_FAX) :
                new ObjectParameter("MERCHANT_FAX", typeof(string));
    
            var mERCHANT_EMAIL1Parameter = mERCHANT_EMAIL1 != null ?
                new ObjectParameter("MERCHANT_EMAIL1", mERCHANT_EMAIL1) :
                new ObjectParameter("MERCHANT_EMAIL1", typeof(string));
    
            var mERCHANT_EMAIL2Parameter = mERCHANT_EMAIL2 != null ?
                new ObjectParameter("MERCHANT_EMAIL2", mERCHANT_EMAIL2) :
                new ObjectParameter("MERCHANT_EMAIL2", typeof(string));
    
            var mERCHANT_EMAIL3Parameter = mERCHANT_EMAIL3 != null ?
                new ObjectParameter("MERCHANT_EMAIL3", mERCHANT_EMAIL3) :
                new ObjectParameter("MERCHANT_EMAIL3", typeof(string));
    
            var mERCHANT_BANK_ACCOUNTParameter = mERCHANT_BANK_ACCOUNT != null ?
                new ObjectParameter("MERCHANT_BANK_ACCOUNT", mERCHANT_BANK_ACCOUNT) :
                new ObjectParameter("MERCHANT_BANK_ACCOUNT", typeof(string));
    
            var mERCHANT_LAST_DAY_ACTIVATEParameter = mERCHANT_LAST_DAY_ACTIVATE.HasValue ?
                new ObjectParameter("MERCHANT_LAST_DAY_ACTIVATE", mERCHANT_LAST_DAY_ACTIVATE) :
                new ObjectParameter("MERCHANT_LAST_DAY_ACTIVATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UpdateMerchant", mERCHANT_NUMBERParameter, mERCHANT_NAMEParameter, mERCHANT_TYPEParameter, mERCHANT_TELEPHONE1Parameter, mERCHANT_TELEPHONE2Parameter, mERCHANT_TELEPHONE3Parameter, mERCHANT_CITYParameter, mERCHANT_DISTRICTParameter, mERCHANT_STREETParameter, mERCHANT_STEET_NUMBERParameter, mERCHANT_REGIONParameter, mERCHANT_OWNERParameter, mERCHANT_FAXParameter, mERCHANT_EMAIL1Parameter, mERCHANT_EMAIL2Parameter, mERCHANT_EMAIL3Parameter, mERCHANT_BANK_ACCOUNTParameter, mERCHANT_LAST_DAY_ACTIVATEParameter);
        }
    
        public virtual int Sp_UpdateMessageStatus(string idMessage)
        {
            var idMessageParameter = idMessage != null ?
                new ObjectParameter("idMessage", idMessage) :
                new ObjectParameter("idMessage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UpdateMessageStatus", idMessageParameter);
        }
    
        public virtual int Sp_UpdatePassword(string account, string oldPassword, string newPassword, string confirmPassword)
        {
            var accountParameter = account != null ?
                new ObjectParameter("account", account) :
                new ObjectParameter("account", typeof(string));
    
            var oldPasswordParameter = oldPassword != null ?
                new ObjectParameter("oldPassword", oldPassword) :
                new ObjectParameter("oldPassword", typeof(string));
    
            var newPasswordParameter = newPassword != null ?
                new ObjectParameter("newPassword", newPassword) :
                new ObjectParameter("newPassword", typeof(string));
    
            var confirmPasswordParameter = confirmPassword != null ?
                new ObjectParameter("confirmPassword", confirmPassword) :
                new ObjectParameter("confirmPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UpdatePassword", accountParameter, oldPasswordParameter, newPasswordParameter, confirmPasswordParameter);
        }
    
        public virtual int Sp_Updatestatusmerchant(string merchant, string status)
        {
            var merchantParameter = merchant != null ?
                new ObjectParameter("merchant", merchant) :
                new ObjectParameter("merchant", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Updatestatusmerchant", merchantParameter, statusParameter);
        }
    
        public virtual int TONGHOP_TRANSACTION_DETAIL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TONGHOP_TRANSACTION_DETAIL");
        }
    
        public virtual ObjectResult<Sp_SearchAgent_Result> Sp_SearchAgent(string agentNumber, string agentBankNumber, string agentDistrict, Nullable<System.DateTime> agentApprovedDate, string merchantType)
        {
            var agentNumberParameter = agentNumber != null ?
                new ObjectParameter("agentNumber", agentNumber) :
                new ObjectParameter("agentNumber", typeof(string));
    
            var agentBankNumberParameter = agentBankNumber != null ?
                new ObjectParameter("agentBankNumber", agentBankNumber) :
                new ObjectParameter("agentBankNumber", typeof(string));
    
            var agentDistrictParameter = agentDistrict != null ?
                new ObjectParameter("agentDistrict", agentDistrict) :
                new ObjectParameter("agentDistrict", typeof(string));
    
            var agentApprovedDateParameter = agentApprovedDate.HasValue ?
                new ObjectParameter("agentApprovedDate", agentApprovedDate) :
                new ObjectParameter("agentApprovedDate", typeof(System.DateTime));
    
            var merchantTypeParameter = merchantType != null ?
                new ObjectParameter("merchantType", merchantType) :
                new ObjectParameter("merchantType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_SearchAgent_Result>("Sp_SearchAgent", agentNumberParameter, agentBankNumberParameter, agentDistrictParameter, agentApprovedDateParameter, merchantTypeParameter);
        }
    
        public virtual int Sp_SendMessage(string sender, string receiver, string description)
        {
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            var receiverParameter = receiver != null ?
                new ObjectParameter("receiver", receiver) :
                new ObjectParameter("receiver", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_SendMessage", senderParameter, receiverParameter, descriptionParameter);
        }
    
        public virtual ObjectResult<Sp_Revenue_Result> Sp_Revenue(string agent, string merchant, string loaiMerchant, Nullable<System.DateTime> ngay, Nullable<int> thang, Nullable<int> namthang, Nullable<int> quy, Nullable<int> namquy, Nullable<int> nam)
        {
            var agentParameter = agent != null ?
                new ObjectParameter("agent", agent) :
                new ObjectParameter("agent", typeof(string));
    
            var merchantParameter = merchant != null ?
                new ObjectParameter("merchant", merchant) :
                new ObjectParameter("merchant", typeof(string));
    
            var loaiMerchantParameter = loaiMerchant != null ?
                new ObjectParameter("loaiMerchant", loaiMerchant) :
                new ObjectParameter("loaiMerchant", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namthangParameter = namthang.HasValue ?
                new ObjectParameter("namthang", namthang) :
                new ObjectParameter("namthang", typeof(int));
    
            var quyParameter = quy.HasValue ?
                new ObjectParameter("quy", quy) :
                new ObjectParameter("quy", typeof(int));
    
            var namquyParameter = namquy.HasValue ?
                new ObjectParameter("namquy", namquy) :
                new ObjectParameter("namquy", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Revenue_Result>("Sp_Revenue", agentParameter, merchantParameter, loaiMerchantParameter, ngayParameter, thangParameter, namthangParameter, quyParameter, namquyParameter, namParameter);
        }
    
        public virtual ObjectResult<Sp_Revenue_Option_Result> Sp_Revenue_Option(string agent, string merchant, string loaiMerchant, Nullable<System.DateTime> ngay, Nullable<int> thang, Nullable<int> namthang, Nullable<int> quy, Nullable<int> namquy, Nullable<int> nam)
        {
            var agentParameter = agent != null ?
                new ObjectParameter("agent", agent) :
                new ObjectParameter("agent", typeof(string));
    
            var merchantParameter = merchant != null ?
                new ObjectParameter("merchant", merchant) :
                new ObjectParameter("merchant", typeof(string));
    
            var loaiMerchantParameter = loaiMerchant != null ?
                new ObjectParameter("loaiMerchant", loaiMerchant) :
                new ObjectParameter("loaiMerchant", typeof(string));
    
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namthangParameter = namthang.HasValue ?
                new ObjectParameter("namthang", namthang) :
                new ObjectParameter("namthang", typeof(int));
    
            var quyParameter = quy.HasValue ?
                new ObjectParameter("quy", quy) :
                new ObjectParameter("quy", typeof(int));
    
            var namquyParameter = namquy.HasValue ?
                new ObjectParameter("namquy", namquy) :
                new ObjectParameter("namquy", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Revenue_Option_Result>("Sp_Revenue_Option", agentParameter, merchantParameter, loaiMerchantParameter, ngayParameter, thangParameter, namthangParameter, quyParameter, namquyParameter, namParameter);
        }
    }
}
