//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGENT()
        {
            this.MERCHANT = new HashSet<MERCHANT>();
        }
    
        public string AGENT_NUMBER { get; set; }
        public string AGENT_NAME { get; set; }
        public string AGENT_TELEPHONE1 { get; set; }
        public string AGENT_TELEPHONE2 { get; set; }
        public string AGENT_TELEPHONE3 { get; set; }
        public string AGENT_CITY { get; set; }
        public string AGENT_DISTRICT { get; set; }
        public string AGENT_STREET { get; set; }
        public string AGENT_STREET_NUMBER { get; set; }
        public string AGENT_REGION { get; set; }
        public string AGENT_OWNER { get; set; }
        public string AGENT_FAX { get; set; }
        public string AGENT_EMAIL_1 { get; set; }
        public string AGENT_EMAIL_2 { get; set; }
        public string AGENT_EMAIL_3 { get; set; }
        public string AGENT_BANK_ACCOUNT { get; set; }
        public string BACKEND_PROCESSOR { get; set; }
        public string AGENT_STATUS { get; set; }
        public System.DateTime AGENT_APPR0VE_DATE { get; set; }
        public Nullable<System.DateTime> AGENT_FIRST_DATE_ACTIVATE { get; set; }
        public Nullable<System.DateTime> AGENT_LAST_DAY_ACTIVATE { get; set; }
    
        public virtual PROCESSOR PROCESSOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MERCHANT> MERCHANT { get; set; }
    }
}
