//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERCHANT_SUMMARY
    {
        public string MERCHANT_NUMBER { get; set; }
        public System.DateTime REPORT_DATE { get; set; }
        public int TRANSACTION_COUNT { get; set; }
        public int SALES_COUNT { get; set; }
        public decimal SALES_AMOUNT { get; set; }
        public int RETURN_COUNT { get; set; }
        public decimal RETURN_AMOUNT { get; set; }
        public int KEYED_COUNT { get; set; }
        public decimal NET_AMOUNT { get; set; }
        public decimal KEY_AMOUNT { get; set; }
        public int FOREIGN_CARD_COUNT { get; set; }
        public int FOREIGN_CARD_SALES_COUNT { get; set; }
        public int FOREIGN_CARD_RETURN_COUNT { get; set; }
        public decimal FOREIGN_CARD_SALES_AMOUNT { get; set; }
        public decimal FOREIGN_CARD_RETURN_AMOUNT { get; set; }
        public decimal FOREIGN_CARD_NET_AMOUNT { get; set; }
        public int DEBIT_CARD_COUNT { get; set; }
        public int DEBIT_CARD_SALES_COUNT { get; set; }
        public int DEBIT_CARD_RETURN_COUNT { get; set; }
        public decimal DEBIT_CARD_SALES_AMOUNT { get; set; }
        public decimal DEBIT_CARD_RETURN_AMOUNT { get; set; }
        public decimal DEBIT_CARD_NET_AMOUNT { get; set; }
        public int VISA_CARD_COUNT { get; set; }
        public int VISA_CARD_SALES_COUNT { get; set; }
        public int VISA_CARD_RETURN_COUNT { get; set; }
        public decimal VISA_CARD_SALES_AMOUNT { get; set; }
        public decimal VISA_CARD_RETURN_AMOUNT { get; set; }
        public decimal VISA_CARD_NET_AMOUNT { get; set; }
        public int MASTER_CARD_COUNT { get; set; }
        public int MASTER_CARD_SALES_COUNT { get; set; }
        public int MASTER_CARD_RETURN_COUNT { get; set; }
        public decimal MASTER_CARD_SALES_AMOUNT { get; set; }
        public decimal MASTER_CARD_RETURN_AMOUNT { get; set; }
        public decimal MASTER_CARD_NET_AMOUNT { get; set; }
        public int AMERICANEXPRESS_CARD_COUNT { get; set; }
        public int AMERICANEXPRESS_CARD_SALES_COUNT { get; set; }
        public int AMERICANEXPRESS_CARD_RETURN_COUNT { get; set; }
        public decimal AMERICANEXPRESS_CARD_SALES_AMOUNT { get; set; }
        public decimal AMERICANEXPRESS_CARD_RETURN_AMOUNT { get; set; }
        public decimal AMERICANEXPRESS_CARD_NET_AMOUNT { get; set; }
        public int DISCOVERY_CARD_COUNT { get; set; }
        public int DISCOVERY_CARD_SALES_COUNT { get; set; }
        public int DISCOVERY_CARD_RETURN_COUNT { get; set; }
        public decimal DISCOVERY_CARD_SALES_AMOUNT { get; set; }
        public decimal DISCOVERY_CARD_RETURN_AMOUNT { get; set; }
        public decimal DISCOVERY_CARD_NET_AMOUNT { get; set; }
        public int OTHER_CARD_COUNT { get; set; }
        public int OTHER_CARD_SALES_COUNT { get; set; }
        public int OTHER_CARD_RETURN_COUNT { get; set; }
        public decimal OTHER_CARD_SALES_AMOUNT { get; set; }
        public decimal OTHER_CARD_RETURN_AMOUNT { get; set; }
        public decimal OTHER_CARD_NET_AMOUNT { get; set; }
    
        public virtual MERCHANT MERCHANT { get; set; }
    }
}
