//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETRIVAL
    {
        public string RETRIVAL_ID { get; set; }
        public string TRANSACTION_ID { get; set; }
        public System.DateTime RETRIVAL_DATE { get; set; }
        public string RETRIVAL_DESCRIPTION { get; set; }
    }
}
